---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-football
  labels:
    app: vm-football
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-football
  template:
    metadata:
      labels:
        app: vm-football
    spec:
      containers:
      - name: vm-football
        image: vmach/football:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /football/resources/players
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: vm-football
spec:
  selector:
    app: vm-football
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31089
  type: NodePort
